# Generated by Selenium IDE
require "selenium-webdriver"
require "json"

describe "UserAuth" do
  before(:all) do
    @name = "user_x2"
    @surname = "user_x2"
    @nick = "user_x2"
    @mail = "user_x2@x2.com"
    @password = "Qwerty12345?-"

    @name2 = "user_y2"
    @surname2 = "user_y2"
    @nick2 = "user_y2"
    @mail2 = "user_y2@y2"
  end

  before(:each) do
    @driver = Selenium::WebDriver.for :firefox
    @vars = {}
  end
  after(:each) do
    #@driver.quit
  end

it "createAccount_x" do
    @driver.get("http://localhost:3000/users/sign_in")
    @driver.find_element(:link_text, "Create an Account").click

    # Create new account
    create_account(@driver, @name, @surname, @nick, @mail, @password)
    sleep(2)

    # Logout
    logout(@driver)
end

it "createAccount_y" do
    @driver.get("http://localhost:3000/users/sign_in")
    @driver.find_element(:link_text, "Create an Account").click

    # Create new account
    create_account(@driver, @name2, @surname2, @nick2, @mail2, @password)
    sleep(2)

    # Logout
    logout(@driver)
end

it "createSharedProject" do
    @driver.get("http://localhost:3000/users/sign_in")
    login(@driver, @mail, @password)

    @driver.find_element(:css, '#link_to_projects > span').click
    @driver.find_element(:id, 'btn_create_project').click
    @driver.find_element(:id, 'project_name').click
    @driver.find_element(:id, 'project_name').send_keys('project test')
    @driver.find_element(:id, 'project_description').click
    @driver.find_element(:id, 'project_description').send_keys('project test shared with other user')
    @driver.find_element(:id, 'btn_project_submit').click

    @driver.find_element(:id, 'project_header_option_1').click
    @driver.find_element(:id, 'project_link_1').click
    @driver.find_element(:id, 'btn_management_project').click
    @driver.find_element(:id, 'btn_invite_project').click
    @driver.find_element(:id, 'user_email').click
    @driver.find_element(:id, 'user_email').send_keys(@mail2)
    @driver.find_element(:id, 'btn_invitation_submit').click

    invitation = @driver.find_element(:xpath,'/html/body/div[1]/div[3]/div/div[2]/div[2]/div[2]/div/div/div/div/div[1]')
    expect(invitation).not_to be_nil

    # Logout
    logout(@driver)
end

it "checkNotification" do
    @driver.get("http://localhost:3000/users/sign_in")
    login(@driver, @mail2, @password)

    @driver.find_element(:css, '#alertsDropdown > .fas').click
    notification_number = @driver.find_element(:xpath,'/html/body/div[1]/div[3]/div/nav/ul/li[1]/a/span')
    expect(notification_number).not_to be_nil

    @driver.find_element(:id, 'link_to_show_all_alerts').click
     email = @driver.find_element(:xpath,'/html/body/div/div[3]/div/div[2]/div/div')
    expect(email).not_to be_nil

    @driver.find_element(:id, 'btn_accept_1').click

    # Logout
    logout(@driver)
end

it "checkNewCollaborator" do
    @driver.get("http://localhost:3000/users/sign_in")
    login(@driver, @mail, @password)

   @driver.find_element(:css, '#link_to_projects > span').click
    @driver.find_element(:id, 'project_header_option_1').click
    @driver.find_element(:id, 'project_link_1').click
    @driver.find_element(:id, 'btn_management_project').click

     collaborators = @driver.find_element(:xpath,'/html/body/div[1]/div[3]/div/div[2]/div[2]/div[1]/div[2]/div/div/div/div[1]/div[1]')
    expect(collaborators).not_to be_nil

end


it "leaveProject" do
    @driver.get("http://localhost:3000/users/sign_in")
    login(@driver, @mail2, @password)

    @driver.find_element(:css, '#link_to_projects > span').click
    @driver.find_element(:id, 'project_header_option_1').click
    @driver.find_element(:id, 'project_link_1').click
    @driver.find_element(:id, 'btn_management_project').click
    @driver.find_element(:id, 'btn_delete_project').click
    expect(@driver.switch_to.alert.text).to eq('Are you sure?')
    @driver.switch_to.alert.accept
    @driver.find_element(:id, 'app_title_link').click

    # Logout
    logout(@driver)

end


it "deleteProject" do
    @driver.get("http://localhost:3000/users/sign_in")
    login(@driver, @mail, @password)

    @driver.find_element(:css, '#link_to_projects > span').click
    @driver.find_element(:id, 'project_header_option_1').click
    @driver.find_element(:id, 'project_link_1').click
    @driver.find_element(:id, 'btn_management_project').click
    @driver.find_element(:id, 'btn_delete_project').click
    expect(@driver.switch_to.alert.text).to eq('Are you sure?')
    @driver.switch_to.alert.accept
    @driver.find_element(:id, 'app_title_link').click

    # Logout
    logout(@driver)

end

it "deleteAccount_x" do
    @driver.get("http://localhost:3000/users/sign_in")
    login(@driver, @mail, @password)
    sleep(1)

    @driver.find_element(:id, "user_profile_photo").click
    @driver.find_element(:id, "user_account_edit").click

    sleep(1)
    @driver.find_element(:id, "user_account_delete").click
    expect(@driver.switch_to.alert.text).to eq("Are you sure?")
    @driver.switch_to.alert.accept
    sleep(1)
end

it "deleteAccount_y" do
    @driver.get("http://localhost:3000/users/sign_in")
    login(@driver, @mail2, @password)
    sleep(1)

    @driver.find_element(:id, "user_profile_photo").click
    @driver.find_element(:id, "user_account_edit").click

    sleep(1)
    @driver.find_element(:id, "user_account_delete").click
    expect(@driver.switch_to.alert.text).to eq("Are you sure?")
    @driver.switch_to.alert.accept
    sleep(1)
end
end

def create_account(driver, name, surname, nick, mail, password)
  driver.find_element(:id, "user_first_name").click
  driver.find_element(:id, "user_first_name").send_keys(name)
  driver.find_element(:id, "user_surname").click
  driver.find_element(:id, "user_surname").send_keys(surname)
  driver.find_element(:id, "user_username").click
  driver.find_element(:id, "user_username").send_keys(nick)
  driver.find_element(:id, "user_email").click
  driver.find_element(:id, "user_email").send_keys(mail)
  driver.find_element(:id, "user_password").click
  driver.find_element(:id, "user_password").send_keys(password)
  driver.find_element(:id, "user_password_confirmation").click
  driver.find_element(:id, "user_password_confirmation").send_keys(password)
  driver.find_element(:name, "commit").click
end

def login(driver, email, password)
  driver.find_element(:id, "user_email").click
  driver.find_element(:id, "user_email").send_keys(email)
  driver.find_element(:id, "user_password").click
  driver.find_element(:id, "user_password").send_keys(password)
  @driver.find_element(:name, "commit").click
end

def logout(driver)
  driver.find_element(:id, "user_profile_photo").click
  driver.find_element(:id, "user_logout").click
  sleep(1)

  # Confirm
  driver.find_element(:id, "user_logout_confirm").click
  sleep(1)

  #Check that we are in login page
  pwd_error = @driver.find_elements(:id, "btn_login")
  expect(pwd_error.length).to eq(1)
end
