# Generated by Selenium IDE
require 'selenium-webdriver'
require 'json'

describe 'Creartarea' do
  before(:each) do
    @driver = Selenium::WebDriver.for :firefox
    @vars = {}
  end
  after(:each) do
    #@driver.quit
  end

  it 'creartarea' do
    @driver.get('http://localhost:3000/')

    # Get tasks pending
    pending = @driver.find_element(:id, 'lblPendingTasks').text
    
    #Click on add new task
    element = @driver.find_element(:id, 'btn_addTask').click

    #@driver.action.move_to_element(element).perform
    #element = @driver.find_element(By.CSS_SELECTOR, 'body')
    #@driver.action.move_to_element(element, 0, 0).perform
    @driver.find_element(:id, 'task_name').click
    @driver.find_element(:id, 'task_name').send_keys('Tarea de prueba')
    @driver.find_element(:id, 'task_description').click
    @driver.find_element(:id, 'task_description').send_keys('Descripción para la tarea')
    @driver.find_element(:id, 'task_priority').click
    dropdown = @driver.find_element(:id, 'task_priority')
    dropdown.find_element(:xpath, "//option[. = 'Medium']").click
    @driver.find_element(:id, 'task_deadline').send_keys('2020-03-20')
    @driver.find_element(:id, 'btnSubmit_newTask').click

    expected = (pending.to_i + 1).to_s
    sleep(1)
    expect(@driver.find_element(:id, 'lblPendingTasks').text).to eq (expected)
   
    #@driver.find_element(:name, 'commit').click
  end
end
