# Generated by Selenium IDE
require 'selenium-webdriver'
require 'json'

describe 'User' do
  before(:each) do
    @driver = Selenium::WebDriver.for :firefox
    @vars = {}
  end
  after(:each) do
    @driver.quit
  end

  it 'user' do

    @driver.get('http://localhost:3000/users/sign_in')
    @driver.find_element(:link_text, 'Create an Account').click

    name = 'test'
    surname = 'user'
    complete = name + " "+surname
    nick = 'testUser' 
    mail = 'test@user.com'
    password = 'Qwerty12345?-'

    # Create new account

    @driver.find_element(:id, 'user_first_name').click
    @driver.find_element(:id, 'user_first_name').send_keys(name)
    @driver.find_element(:id, 'user_surname').click
    @driver.find_element(:id, 'user_surname').send_keys(surname)
    @driver.find_element(:id, 'user_username').click
    @driver.find_element(:id, 'user_username').send_keys(nick)
    @driver.find_element(:id, 'user_email').click
    @driver.find_element(:id, 'user_email').send_keys(mail)
    @driver.find_element(:id, 'user_password').click
    @driver.find_element(:id, 'user_password').send_keys(password)
    @driver.find_element(:id, 'user_password_confirmation').click
    @driver.find_element(:id, 'user_password_confirmation').send_keys(password)
    @driver.find_element(:name, 'commit').click

    # Read account information

    @driver.find_element(:css, '.img-profile').click
    @driver.find_element(:id, 'user_account_edit').click

    first_name = @driver.find_element(:xpath, "//input[contains(@name, 'user[first_name]')]").attribute('value')
    expect(first_name).to eq(complete) 

    last_name = @driver.find_element(:xpath, "//input[contains(@name, 'user[surname]')]").attribute('value')
    expect(last_name).to eq(surname)

    username = @driver.find_element(:xpath, "//input[contains(@name, 'user[username]')]").attribute('value')
    expect(username).to eq(nick)

    usermail = @driver.find_element(:xpath, "//input[contains(@name, 'user[email]')]").attribute('value')
    expect(usermail).to eq(mail)

    # Edit account information

    nameEdit = 'testEDIT'
    surnameEdit = 'userEDIT'
    nickEdit = 'testUserEDIT' 
    completeEdit = nameEdit + " "+surnameEdit

    @driver.find_element(:id, 'user_first_name').click
    @driver.find_element(:id, 'user_first_name').send_keys(nameEdit)
    @driver.find_element(:id, 'user_surname').click
    @driver.find_element(:id, 'user_surname').send_keys(surnameEdit)
    @driver.find_element(:id, 'user_username').click
    @driver.find_element(:id, 'user_username').send_keys(nickEdit)
    @driver.find_element(:name, 'commit').click

    # Logout

    @driver.find_element(:css, '.img-profile').click
    @driver.find_element(:link_text, 'Logout').click
    @driver.find_element(:id, 'user_logout_modal').click

    # Login

    @driver.find_element(:id, 'user_email').click
    @driver.find_element(:id, 'user_email').send_keys('test@user.com')
    @driver.find_element(:id, 'user_password').click
    @driver.find_element(:id, 'user_password').send_keys('Qwerty12345?-')
    @driver.find_element(:name, 'commit').click

    # Read edited information

    @driver.find_element(:css, '.img-profile').click
    @driver.find_element(:id, 'user_account_edit').click

    first_nameE = @driver.find_element(:xpath, "//input[contains(@name, 'user[first_name]')]").attribute('value')
    expect(first_nameE).to eq(completeEdit)

    last_nameE = @driver.find_element(:xpath, "//input[contains(@name, 'user[surname]')]").attribute('value')
    expect(last_nameE).to eq(surnameEdit)

    usernameE = @driver.find_element(:xpath, "//input[contains(@name, 'user[username]')]").attribute('value')
    expect(usernameE).to eq(nickEdit)

    # Delete account

    @driver.find_element(:id, 'user_account_delete').click
    expect(@driver.switch_to.alert.text).to eq('Are you sure?')
    @driver.switch_to.alert.accept
  end
end
